### ISSUE TITLE
How to blur view with transparent background

### ISSUE THREAD

**Issue by jackyhieu1211-hn** [patrickfav/Dali#12]
Hello admin

I use background is image. Library worked good. But I use background is transparent (#66000000). Library not work. Please help me. thank you very much

           <androidx.appcompat.widget.AppCompatImageView
            android:id="@+id/viewBlur"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:background="#66000000"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toTopOf="parent"
    />

and use

      Dali.create(this).load(pageControlProduct).blurRadius(20)
            .downScale(2).concurrent().reScale().skipCache().into(viewBlur);

**Comment by patrickfav** [comment]
Hi,

The code example seems to be from this project: https://github.com/jgabrielfreita
Please contact them for support on your issue.

**Comment by jackyhieu1211-hn** [comment]
Sorry sir. I copied the mistake. I edit comment. please check again
