### ISSUE TITLE
Unable to publish app to playstore due to no 64-bit support

### ISSUE THREAD

**Issue by mani516** [patrickfav/Dali#16]
Since app updates are not allowed without including 64-bit support, One of our apps using this library cannot be published to play store as this library doesnt have 64-bit supported native library files (.so). Can you fix this?
References:
https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html
https://developer.android.com/distribute/best-practices/develop/64-bit

**Comment by patrickfav** [comment]
So there are no `.so` files, only Renderscript. After some research it seems that we need at least version 22: https://stackoverflow.com/a/56477402/774398

I will update and release a new version. I would invite you to test this new release and verify that this fix works.

**Comment by mani516** [comment]
Thanks for the reply.

When can we expect this to be released?

Right now, we had to disable the feature which uses this library and able to successfully publish the app to playstore. But now, we should decide on whether to go for alternatives or wait for the next release of this library. So it would be helpful, if you can give us some rough estimate.

> I will update and release a new version. I would invite you to test this new release and verify that this fix works.

Sure. I would test it when the release is made.

**Comment by patrickfav** [comment]
I'll probably be able to release it EOD

**Comment by patrickfav** [comment]
New version 0.3.8 is out with updated renderscript target, @mani516 if you could, please check it this now works with the 64 bit requirements.

https://github.com/patrickfav/Dali/releases/tag/v0.3.8

**Comment by mani516** [comment]
Hey @patrickfav 
I have tested the latest version. Now the issue has been fixed.
Thanks for the quick response.

**Comment by patrickfav** [comment]
Sure. Have a good release.

Cheers.
